### PR TITLE
Atom media

### PR DESCRIPTION
**Pull request by GeniusRUS**
- Updating dependencies
- Added media source for Atom
- Added final modifier in many places
- Improved read data from incorrect formatted data property (lead space brokes parsing operation)
- Improved getting image and author for AtomEntry

### CODE REVIEW

**Comment by GeniusRUS** [comment]
This is also can fix #6 issue

**Comment by einmalfel** [comment]
Hi there! Thanks for your PR, I like it overall, but could you please reformat it to make it follow [google code style](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation) for java?

**Comment by einmalfel** [comment]
sorry, but I still can see tabs instead of spaces in PR diff

**Comment by unitbean** [comment]
Hello! I don't want to be the guy who constantly asks, but still, is the release planned taking into account the accepted changes in the pull request?

**Comment by GeniusRUS** [comment]
Hello! I don't want to be the guy who constantly asks, but still, is the release planned taking into account the accepted changes in the pull request?

**Comment by unitbean** [comment]
пересылаемое письмо

**Pull request merged**
